# In _config.yml
title: Digital Tibetan
author: Digital Tibetan Community
logo: Images/DigitalTibetanLogo.png
copyright: "2022"
execute:
  execute_notebooks: force

exclude_pattern: [README.md]

launch_buttons:
  thebe                  : true
  colab_url: "https://colab.research.google.com"

repository:
  url: https://github.com/digitaltibetan/DigitalTibetan
  branch: main

parse:
  myst_enable_extensions:
    # don't forget to list any other extensions you want enabled,
    # including those that are enabled by default!
    - html_image
html:
  favicon                   : Images/favicon.ico
  use_edit_page_button : true
  use_repository_button : true
  use_issue_button : true

sphinx:
  # mermaid_params = ['--theme', 'forest', '--width', '600', '--backgroundColor', 'transparent']
  config:
    mermaid_params: ['--width', '100%']
    html_extra_path: ['resources']
    mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  extra_extensions:
    - sphinxcontrib.mermaid
