# In _config.yml
title: Digital Tibetan
author: Digital Tibetan Community
logo: Images/DigitalTibetanLogo.png
copyright: "2022"
execute:
  execute_notebooks: force

exclude_pattern: [README.md]

launch_buttons:
  thebe                  : true
  colab_url: "https://colab.research.google.com"

repository:
  url: https://github.com/digitaltibetan/DigitalTibetan
  branch: main

html:
  favicon                   : Images/favicon.ico
  use_edit_page_button : true
  use_repository_button : true
  use_issue_button : true

sphinx:
  extra_extensions:
    - sphinxcontrib.mermaid
#   config:
#     html_theme: alabaster # pydata_sphinx_theme

# Add a bibtex file so that we can create citations
# bibtex_bibfiles:
#  - references.bib
